#rpc客户端配置信息
iRpcClient:
  retryTimes: 3
  serverModCluster: true
  serverNode:
    - ip: 127.0.0.1 # 第一个节点是主节点即master节点
      port: 10918
    - ip: 127.0.0.1
      port: 10917
    - ip: 127.0.0.1
      port: 10916
## rpc服务端配置信息
iRpcServer:
  serverPort: 10918
  heartbeat: 60 # min
  nodeName: n2
  groupName: default
  ClusterNode: #如果使用单机，则不配置该项,node从n1开始，n0属于localhost
    - node: n0
      ip: 127.0.0.1
      port: 10916
    - node: n1
      ip: 127.0.0.1
      port: 10917
    - node: n2
      ip: 127.0.0.1
      port: 10918